security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # On garde une config vide ou on définit un provider si vous avez une autre table User (ex: Admin)
        # Pour l'instant, on désactive le provider Patient
        app_user_provider:
            memory: null

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # On désactive le login form car plus de password
            # form_login: ... 

    access_control:
        # On désactive les restrictions sur le dashboard pour l'instant
        # - { path: ^/dashboard, roles: ROLE_USER }
